// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package top.weixiansen574.bilibiliArchive.biliApis.protobuf.danmaku;

public interface DanmakuEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.community.service.dm.v1.DanmakuEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
   */
  java.util.List<DanmakuElem>
      getElemsList();
  /**
   * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
   */
  DanmakuElem getElems(int index);
  /**
   * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
   */
  int getElemsCount();
  /**
   * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
   */
  java.util.List<? extends DanmakuElemOrBuilder>
      getElemsOrBuilderList();
  /**
   * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
   */
  DanmakuElemOrBuilder getElemsOrBuilder(
      int index);
}
