// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package top.weixiansen574.bilibiliArchive.biliApis.protobuf.danmaku;

/**
 * Protobuf type {@code bilibili.community.service.dm.v1.DanmakuEvent}
 */
public final class DanmakuEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bilibili.community.service.dm.v1.DanmakuEvent)
    DanmakuEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DanmakuEvent.newBuilder() to construct.
  private DanmakuEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DanmakuEvent() {
    elems_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new DanmakuEvent();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Danmaku.internal_static_bilibili_community_service_dm_v1_DanmakuEvent_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Danmaku.internal_static_bilibili_community_service_dm_v1_DanmakuEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            DanmakuEvent.class, Builder.class);
  }

  public static final int ELEMS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<DanmakuElem> elems_;
  /**
   * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
   */
  @Override
  public java.util.List<DanmakuElem> getElemsList() {
    return elems_;
  }
  /**
   * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
   */
  @Override
  public java.util.List<? extends DanmakuElemOrBuilder>
      getElemsOrBuilderList() {
    return elems_;
  }
  /**
   * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
   */
  @Override
  public int getElemsCount() {
    return elems_.size();
  }
  /**
   * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
   */
  @Override
  public DanmakuElem getElems(int index) {
    return elems_.get(index);
  }
  /**
   * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
   */
  @Override
  public DanmakuElemOrBuilder getElemsOrBuilder(
      int index) {
    return elems_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < elems_.size(); i++) {
      output.writeMessage(1, elems_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < elems_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, elems_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof DanmakuEvent)) {
      return super.equals(obj);
    }
    DanmakuEvent other = (DanmakuEvent) obj;

    if (!getElemsList()
        .equals(other.getElemsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getElemsCount() > 0) {
      hash = (37 * hash) + ELEMS_FIELD_NUMBER;
      hash = (53 * hash) + getElemsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static DanmakuEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DanmakuEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DanmakuEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DanmakuEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DanmakuEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DanmakuEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DanmakuEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DanmakuEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static DanmakuEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static DanmakuEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static DanmakuEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DanmakuEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(DanmakuEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bilibili.community.service.dm.v1.DanmakuEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.community.service.dm.v1.DanmakuEvent)
      DanmakuEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Danmaku.internal_static_bilibili_community_service_dm_v1_DanmakuEvent_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Danmaku.internal_static_bilibili_community_service_dm_v1_DanmakuEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DanmakuEvent.class, Builder.class);
    }

    // Construct using top.weixiansen574.bilibiliArchive.biliApis.protobuf.danmaku.DanmakuEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (elemsBuilder_ == null) {
        elems_ = java.util.Collections.emptyList();
      } else {
        elems_ = null;
        elemsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Danmaku.internal_static_bilibili_community_service_dm_v1_DanmakuEvent_descriptor;
    }

    @Override
    public DanmakuEvent getDefaultInstanceForType() {
      return DanmakuEvent.getDefaultInstance();
    }

    @Override
    public DanmakuEvent build() {
      DanmakuEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public DanmakuEvent buildPartial() {
      DanmakuEvent result = new DanmakuEvent(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(DanmakuEvent result) {
      if (elemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          elems_ = java.util.Collections.unmodifiableList(elems_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.elems_ = elems_;
      } else {
        result.elems_ = elemsBuilder_.build();
      }
    }

    private void buildPartial0(DanmakuEvent result) {
      int from_bitField0_ = bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DanmakuEvent) {
        return mergeFrom((DanmakuEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DanmakuEvent other) {
      if (other == DanmakuEvent.getDefaultInstance()) return this;
      if (elemsBuilder_ == null) {
        if (!other.elems_.isEmpty()) {
          if (elems_.isEmpty()) {
            elems_ = other.elems_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureElemsIsMutable();
            elems_.addAll(other.elems_);
          }
          onChanged();
        }
      } else {
        if (!other.elems_.isEmpty()) {
          if (elemsBuilder_.isEmpty()) {
            elemsBuilder_.dispose();
            elemsBuilder_ = null;
            elems_ = other.elems_;
            bitField0_ = (bitField0_ & ~0x00000001);
            elemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getElemsFieldBuilder() : null;
          } else {
            elemsBuilder_.addAllMessages(other.elems_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              DanmakuElem m =
                  input.readMessage(
                      DanmakuElem.parser(),
                      extensionRegistry);
              if (elemsBuilder_ == null) {
                ensureElemsIsMutable();
                elems_.add(m);
              } else {
                elemsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<DanmakuElem> elems_ =
      java.util.Collections.emptyList();
    private void ensureElemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        elems_ = new java.util.ArrayList<DanmakuElem>(elems_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        DanmakuElem, DanmakuElem.Builder, DanmakuElemOrBuilder> elemsBuilder_;

    /**
     * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
     */
    public java.util.List<DanmakuElem> getElemsList() {
      if (elemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(elems_);
      } else {
        return elemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
     */
    public int getElemsCount() {
      if (elemsBuilder_ == null) {
        return elems_.size();
      } else {
        return elemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
     */
    public DanmakuElem getElems(int index) {
      if (elemsBuilder_ == null) {
        return elems_.get(index);
      } else {
        return elemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
     */
    public Builder setElems(
        int index, DanmakuElem value) {
      if (elemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureElemsIsMutable();
        elems_.set(index, value);
        onChanged();
      } else {
        elemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
     */
    public Builder setElems(
        int index, DanmakuElem.Builder builderForValue) {
      if (elemsBuilder_ == null) {
        ensureElemsIsMutable();
        elems_.set(index, builderForValue.build());
        onChanged();
      } else {
        elemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
     */
    public Builder addElems(DanmakuElem value) {
      if (elemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureElemsIsMutable();
        elems_.add(value);
        onChanged();
      } else {
        elemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
     */
    public Builder addElems(
        int index, DanmakuElem value) {
      if (elemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureElemsIsMutable();
        elems_.add(index, value);
        onChanged();
      } else {
        elemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
     */
    public Builder addElems(
        DanmakuElem.Builder builderForValue) {
      if (elemsBuilder_ == null) {
        ensureElemsIsMutable();
        elems_.add(builderForValue.build());
        onChanged();
      } else {
        elemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
     */
    public Builder addElems(
        int index, DanmakuElem.Builder builderForValue) {
      if (elemsBuilder_ == null) {
        ensureElemsIsMutable();
        elems_.add(index, builderForValue.build());
        onChanged();
      } else {
        elemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
     */
    public Builder addAllElems(
        Iterable<? extends DanmakuElem> values) {
      if (elemsBuilder_ == null) {
        ensureElemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, elems_);
        onChanged();
      } else {
        elemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
     */
    public Builder clearElems() {
      if (elemsBuilder_ == null) {
        elems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        elemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
     */
    public Builder removeElems(int index) {
      if (elemsBuilder_ == null) {
        ensureElemsIsMutable();
        elems_.remove(index);
        onChanged();
      } else {
        elemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
     */
    public DanmakuElem.Builder getElemsBuilder(
        int index) {
      return getElemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
     */
    public DanmakuElemOrBuilder getElemsOrBuilder(
        int index) {
      if (elemsBuilder_ == null) {
        return elems_.get(index);  } else {
        return elemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
     */
    public java.util.List<? extends DanmakuElemOrBuilder>
         getElemsOrBuilderList() {
      if (elemsBuilder_ != null) {
        return elemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(elems_);
      }
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
     */
    public DanmakuElem.Builder addElemsBuilder() {
      return getElemsFieldBuilder().addBuilder(
          DanmakuElem.getDefaultInstance());
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
     */
    public DanmakuElem.Builder addElemsBuilder(
        int index) {
      return getElemsFieldBuilder().addBuilder(
          index, DanmakuElem.getDefaultInstance());
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.DanmakuElem elems = 1;</code>
     */
    public java.util.List<DanmakuElem.Builder>
         getElemsBuilderList() {
      return getElemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        DanmakuElem, DanmakuElem.Builder, DanmakuElemOrBuilder>
        getElemsFieldBuilder() {
      if (elemsBuilder_ == null) {
        elemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            DanmakuElem, DanmakuElem.Builder, DanmakuElemOrBuilder>(
                elems_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        elems_ = null;
      }
      return elemsBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bilibili.community.service.dm.v1.DanmakuEvent)
  }

  // @@protoc_insertion_point(class_scope:bilibili.community.service.dm.v1.DanmakuEvent)
  private static final DanmakuEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DanmakuEvent();
  }

  public static DanmakuEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DanmakuEvent>
      PARSER = new com.google.protobuf.AbstractParser<DanmakuEvent>() {
    @Override
    public DanmakuEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DanmakuEvent> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<DanmakuEvent> getParserForType() {
    return PARSER;
  }

  @Override
  public DanmakuEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

