// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package top.weixiansen574.bilibiliArchive.biliApis.protobuf.danmaku;

/**
 * <pre>
 * DanmakuElem .
 * </pre>
 *
 * Protobuf type {@code bilibili.community.service.dm.v1.DanmakuElem}
 */
public final class DanmakuElem extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bilibili.community.service.dm.v1.DanmakuElem)
    DanmakuElemOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DanmakuElem.newBuilder() to construct.
  private DanmakuElem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DanmakuElem() {
    midHash_ = "";
    content_ = "";
    action_ = "";
    idStr_ = "";
    animation_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new DanmakuElem();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Danmaku.internal_static_bilibili_community_service_dm_v1_DanmakuElem_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Danmaku.internal_static_bilibili_community_service_dm_v1_DanmakuElem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            DanmakuElem.class, Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <pre>
   * 弹幕dmid
   * </pre>
   *
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @Override
  public long getId() {
    return id_;
  }

  public static final int PROGRESS_FIELD_NUMBER = 2;
  private int progress_ = 0;
  /**
   * <pre>
   * 弹幕出现位置(单位ms)
   * </pre>
   *
   * <code>int32 progress = 2;</code>
   * @return The progress.
   */
  @Override
  public int getProgress() {
    return progress_;
  }

  public static final int MODE_FIELD_NUMBER = 3;
  private int mode_ = 0;
  /**
   * <pre>
   * 弹幕类型 1 2 3:普通弹幕 4:底部弹幕 5:顶部弹幕 6:逆向弹幕 7:高级弹幕 8:代码弹幕 9:BAS弹幕(pool必须为2)
   * </pre>
   *
   * <code>int32 mode = 3;</code>
   * @return The mode.
   */
  @Override
  public int getMode() {
    return mode_;
  }

  public static final int FONTSIZE_FIELD_NUMBER = 4;
  private int fontsize_ = 0;
  /**
   * <pre>
   * 弹幕字号
   * </pre>
   *
   * <code>int32 fontsize = 4;</code>
   * @return The fontsize.
   */
  @Override
  public int getFontsize() {
    return fontsize_;
  }

  public static final int COLOR_FIELD_NUMBER = 5;
  private int color_ = 0;
  /**
   * <pre>
   * 弹幕颜色
   * </pre>
   *
   * <code>uint32 color = 5;</code>
   * @return The color.
   */
  @Override
  public int getColor() {
    return color_;
  }

  public static final int MIDHASH_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile Object midHash_ = "";
  /**
   * <pre>
   * 发送者mid hash
   * </pre>
   *
   * <code>string midHash = 6;</code>
   * @return The midHash.
   */
  @Override
  public String getMidHash() {
    Object ref = midHash_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      midHash_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 发送者mid hash
   * </pre>
   *
   * <code>string midHash = 6;</code>
   * @return The bytes for midHash.
   */
  @Override
  public com.google.protobuf.ByteString
      getMidHashBytes() {
    Object ref = midHash_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      midHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile Object content_ = "";
  /**
   * <pre>
   * 弹幕正文
   * </pre>
   *
   * <code>string content = 7;</code>
   * @return The content.
   */
  @Override
  public String getContent() {
    Object ref = content_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 弹幕正文
   * </pre>
   *
   * <code>string content = 7;</code>
   * @return The bytes for content.
   */
  @Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    Object ref = content_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CTIME_FIELD_NUMBER = 8;
  private long ctime_ = 0L;
  /**
   * <pre>
   * 发送时间
   * </pre>
   *
   * <code>int64 ctime = 8;</code>
   * @return The ctime.
   */
  @Override
  public long getCtime() {
    return ctime_;
  }

  public static final int WEIGHT_FIELD_NUMBER = 9;
  private int weight_ = 0;
  /**
   * <pre>
   * 权重 用于屏蔽等级 区间:[1,10]
   * </pre>
   *
   * <code>int32 weight = 9;</code>
   * @return The weight.
   */
  @Override
  public int getWeight() {
    return weight_;
  }

  public static final int ACTION_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile Object action_ = "";
  /**
   * <pre>
   * 动作
   * </pre>
   *
   * <code>string action = 10;</code>
   * @return The action.
   */
  @Override
  public String getAction() {
    Object ref = action_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      action_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 动作
   * </pre>
   *
   * <code>string action = 10;</code>
   * @return The bytes for action.
   */
  @Override
  public com.google.protobuf.ByteString
      getActionBytes() {
    Object ref = action_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      action_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POOL_FIELD_NUMBER = 11;
  private int pool_ = 0;
  /**
   * <pre>
   * 弹幕池 0:普通池 1:字幕池 2:特殊池(代码/BAS弹幕)
   * </pre>
   *
   * <code>int32 pool = 11;</code>
   * @return The pool.
   */
  @Override
  public int getPool() {
    return pool_;
  }

  public static final int IDSTR_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile Object idStr_ = "";
  /**
   * <pre>
   * 弹幕dmid str
   * </pre>
   *
   * <code>string idStr = 12;</code>
   * @return The idStr.
   */
  @Override
  public String getIdStr() {
    Object ref = idStr_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      idStr_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 弹幕dmid str
   * </pre>
   *
   * <code>string idStr = 12;</code>
   * @return The bytes for idStr.
   */
  @Override
  public com.google.protobuf.ByteString
      getIdStrBytes() {
    Object ref = idStr_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      idStr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATTR_FIELD_NUMBER = 13;
  private int attr_ = 0;
  /**
   * <pre>
   * 弹幕属性位(bin求AND)
   * bit0:保护 bit1:直播 bit2:高赞
   * </pre>
   *
   * <code>int32 attr = 13;</code>
   * @return The attr.
   */
  @Override
  public int getAttr() {
    return attr_;
  }

  public static final int ANIMATION_FIELD_NUMBER = 22;
  @SuppressWarnings("serial")
  private volatile Object animation_ = "";
  /**
   * <pre>
   * </pre>
   *
   * <code>string animation = 22;</code>
   * @return The animation.
   */
  @Override
  public String getAnimation() {
    Object ref = animation_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      animation_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>string animation = 22;</code>
   * @return The bytes for animation.
   */
  @Override
  public com.google.protobuf.ByteString
      getAnimationBytes() {
    Object ref = animation_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      animation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (progress_ != 0) {
      output.writeInt32(2, progress_);
    }
    if (mode_ != 0) {
      output.writeInt32(3, mode_);
    }
    if (fontsize_ != 0) {
      output.writeInt32(4, fontsize_);
    }
    if (color_ != 0) {
      output.writeUInt32(5, color_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(midHash_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, midHash_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, content_);
    }
    if (ctime_ != 0L) {
      output.writeInt64(8, ctime_);
    }
    if (weight_ != 0) {
      output.writeInt32(9, weight_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, action_);
    }
    if (pool_ != 0) {
      output.writeInt32(11, pool_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idStr_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, idStr_);
    }
    if (attr_ != 0) {
      output.writeInt32(13, attr_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(animation_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 22, animation_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (progress_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, progress_);
    }
    if (mode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, mode_);
    }
    if (fontsize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, fontsize_);
    }
    if (color_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, color_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(midHash_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, midHash_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, content_);
    }
    if (ctime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, ctime_);
    }
    if (weight_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, weight_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, action_);
    }
    if (pool_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, pool_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idStr_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, idStr_);
    }
    if (attr_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, attr_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(animation_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(22, animation_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof DanmakuElem)) {
      return super.equals(obj);
    }
    DanmakuElem other = (DanmakuElem) obj;

    if (getId()
        != other.getId()) return false;
    if (getProgress()
        != other.getProgress()) return false;
    if (getMode()
        != other.getMode()) return false;
    if (getFontsize()
        != other.getFontsize()) return false;
    if (getColor()
        != other.getColor()) return false;
    if (!getMidHash()
        .equals(other.getMidHash())) return false;
    if (!getContent()
        .equals(other.getContent())) return false;
    if (getCtime()
        != other.getCtime()) return false;
    if (getWeight()
        != other.getWeight()) return false;
    if (!getAction()
        .equals(other.getAction())) return false;
    if (getPool()
        != other.getPool()) return false;
    if (!getIdStr()
        .equals(other.getIdStr())) return false;
    if (getAttr()
        != other.getAttr()) return false;
    if (!getAnimation()
        .equals(other.getAnimation())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + PROGRESS_FIELD_NUMBER;
    hash = (53 * hash) + getProgress();
    hash = (37 * hash) + MODE_FIELD_NUMBER;
    hash = (53 * hash) + getMode();
    hash = (37 * hash) + FONTSIZE_FIELD_NUMBER;
    hash = (53 * hash) + getFontsize();
    hash = (37 * hash) + COLOR_FIELD_NUMBER;
    hash = (53 * hash) + getColor();
    hash = (37 * hash) + MIDHASH_FIELD_NUMBER;
    hash = (53 * hash) + getMidHash().hashCode();
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + CTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCtime());
    hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getWeight();
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + getAction().hashCode();
    hash = (37 * hash) + POOL_FIELD_NUMBER;
    hash = (53 * hash) + getPool();
    hash = (37 * hash) + IDSTR_FIELD_NUMBER;
    hash = (53 * hash) + getIdStr().hashCode();
    hash = (37 * hash) + ATTR_FIELD_NUMBER;
    hash = (53 * hash) + getAttr();
    hash = (37 * hash) + ANIMATION_FIELD_NUMBER;
    hash = (53 * hash) + getAnimation().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static DanmakuElem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DanmakuElem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DanmakuElem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DanmakuElem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DanmakuElem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DanmakuElem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DanmakuElem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DanmakuElem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static DanmakuElem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static DanmakuElem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static DanmakuElem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DanmakuElem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(DanmakuElem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * DanmakuElem .
   * </pre>
   *
   * Protobuf type {@code bilibili.community.service.dm.v1.DanmakuElem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.community.service.dm.v1.DanmakuElem)
      DanmakuElemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Danmaku.internal_static_bilibili_community_service_dm_v1_DanmakuElem_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Danmaku.internal_static_bilibili_community_service_dm_v1_DanmakuElem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DanmakuElem.class, Builder.class);
    }

    // Construct using top.weixiansen574.bilibiliArchive.biliApis.protobuf.danmaku.DanmakuElem.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      progress_ = 0;
      mode_ = 0;
      fontsize_ = 0;
      color_ = 0;
      midHash_ = "";
      content_ = "";
      ctime_ = 0L;
      weight_ = 0;
      action_ = "";
      pool_ = 0;
      idStr_ = "";
      attr_ = 0;
      animation_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Danmaku.internal_static_bilibili_community_service_dm_v1_DanmakuElem_descriptor;
    }

    @Override
    public DanmakuElem getDefaultInstanceForType() {
      return DanmakuElem.getDefaultInstance();
    }

    @Override
    public DanmakuElem build() {
      DanmakuElem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public DanmakuElem buildPartial() {
      DanmakuElem result = new DanmakuElem(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(DanmakuElem result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.progress_ = progress_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.mode_ = mode_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.fontsize_ = fontsize_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.color_ = color_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.midHash_ = midHash_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.content_ = content_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.ctime_ = ctime_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.weight_ = weight_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.action_ = action_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.pool_ = pool_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.idStr_ = idStr_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.attr_ = attr_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.animation_ = animation_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DanmakuElem) {
        return mergeFrom((DanmakuElem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DanmakuElem other) {
      if (other == DanmakuElem.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getProgress() != 0) {
        setProgress(other.getProgress());
      }
      if (other.getMode() != 0) {
        setMode(other.getMode());
      }
      if (other.getFontsize() != 0) {
        setFontsize(other.getFontsize());
      }
      if (other.getColor() != 0) {
        setColor(other.getColor());
      }
      if (!other.getMidHash().isEmpty()) {
        midHash_ = other.midHash_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.getCtime() != 0L) {
        setCtime(other.getCtime());
      }
      if (other.getWeight() != 0) {
        setWeight(other.getWeight());
      }
      if (!other.getAction().isEmpty()) {
        action_ = other.action_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (other.getPool() != 0) {
        setPool(other.getPool());
      }
      if (!other.getIdStr().isEmpty()) {
        idStr_ = other.idStr_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      if (other.getAttr() != 0) {
        setAttr(other.getAttr());
      }
      if (!other.getAnimation().isEmpty()) {
        animation_ = other.animation_;
        bitField0_ |= 0x00002000;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              progress_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              mode_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              fontsize_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              color_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              midHash_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              content_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              ctime_ = input.readInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              weight_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 82: {
              action_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 88: {
              pool_ = input.readInt32();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            case 98: {
              idStr_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 104: {
              attr_ = input.readInt32();
              bitField0_ |= 0x00001000;
              break;
            } // case 104
            case 178: {
              animation_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00002000;
              break;
            } // case 178
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <pre>
     * 弹幕dmid
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     * 弹幕dmid
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 弹幕dmid
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private int progress_ ;
    /**
     * <pre>
     * 弹幕出现位置(单位ms)
     * </pre>
     *
     * <code>int32 progress = 2;</code>
     * @return The progress.
     */
    @Override
    public int getProgress() {
      return progress_;
    }
    /**
     * <pre>
     * 弹幕出现位置(单位ms)
     * </pre>
     *
     * <code>int32 progress = 2;</code>
     * @param value The progress to set.
     * @return This builder for chaining.
     */
    public Builder setProgress(int value) {

      progress_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 弹幕出现位置(单位ms)
     * </pre>
     *
     * <code>int32 progress = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProgress() {
      bitField0_ = (bitField0_ & ~0x00000002);
      progress_ = 0;
      onChanged();
      return this;
    }

    private int mode_ ;
    /**
     * <pre>
     * 弹幕类型 1 2 3:普通弹幕 4:底部弹幕 5:顶部弹幕 6:逆向弹幕 7:高级弹幕 8:代码弹幕 9:BAS弹幕(pool必须为2)
     * </pre>
     *
     * <code>int32 mode = 3;</code>
     * @return The mode.
     */
    @Override
    public int getMode() {
      return mode_;
    }
    /**
     * <pre>
     * 弹幕类型 1 2 3:普通弹幕 4:底部弹幕 5:顶部弹幕 6:逆向弹幕 7:高级弹幕 8:代码弹幕 9:BAS弹幕(pool必须为2)
     * </pre>
     *
     * <code>int32 mode = 3;</code>
     * @param value The mode to set.
     * @return This builder for chaining.
     */
    public Builder setMode(int value) {

      mode_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 弹幕类型 1 2 3:普通弹幕 4:底部弹幕 5:顶部弹幕 6:逆向弹幕 7:高级弹幕 8:代码弹幕 9:BAS弹幕(pool必须为2)
     * </pre>
     *
     * <code>int32 mode = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMode() {
      bitField0_ = (bitField0_ & ~0x00000004);
      mode_ = 0;
      onChanged();
      return this;
    }

    private int fontsize_ ;
    /**
     * <pre>
     * 弹幕字号
     * </pre>
     *
     * <code>int32 fontsize = 4;</code>
     * @return The fontsize.
     */
    @Override
    public int getFontsize() {
      return fontsize_;
    }
    /**
     * <pre>
     * 弹幕字号
     * </pre>
     *
     * <code>int32 fontsize = 4;</code>
     * @param value The fontsize to set.
     * @return This builder for chaining.
     */
    public Builder setFontsize(int value) {

      fontsize_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 弹幕字号
     * </pre>
     *
     * <code>int32 fontsize = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFontsize() {
      bitField0_ = (bitField0_ & ~0x00000008);
      fontsize_ = 0;
      onChanged();
      return this;
    }

    private int color_ ;
    /**
     * <pre>
     * 弹幕颜色
     * </pre>
     *
     * <code>uint32 color = 5;</code>
     * @return The color.
     */
    @Override
    public int getColor() {
      return color_;
    }
    /**
     * <pre>
     * 弹幕颜色
     * </pre>
     *
     * <code>uint32 color = 5;</code>
     * @param value The color to set.
     * @return This builder for chaining.
     */
    public Builder setColor(int value) {

      color_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 弹幕颜色
     * </pre>
     *
     * <code>uint32 color = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearColor() {
      bitField0_ = (bitField0_ & ~0x00000010);
      color_ = 0;
      onChanged();
      return this;
    }

    private Object midHash_ = "";
    /**
     * <pre>
     * 发送者mid hash
     * </pre>
     *
     * <code>string midHash = 6;</code>
     * @return The midHash.
     */
    public String getMidHash() {
      Object ref = midHash_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        midHash_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 发送者mid hash
     * </pre>
     *
     * <code>string midHash = 6;</code>
     * @return The bytes for midHash.
     */
    public com.google.protobuf.ByteString
        getMidHashBytes() {
      Object ref = midHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        midHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 发送者mid hash
     * </pre>
     *
     * <code>string midHash = 6;</code>
     * @param value The midHash to set.
     * @return This builder for chaining.
     */
    public Builder setMidHash(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      midHash_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送者mid hash
     * </pre>
     *
     * <code>string midHash = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMidHash() {
      midHash_ = getDefaultInstance().getMidHash();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送者mid hash
     * </pre>
     *
     * <code>string midHash = 6;</code>
     * @param value The bytes for midHash to set.
     * @return This builder for chaining.
     */
    public Builder setMidHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      midHash_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private Object content_ = "";
    /**
     * <pre>
     * 弹幕正文
     * </pre>
     *
     * <code>string content = 7;</code>
     * @return The content.
     */
    public String getContent() {
      Object ref = content_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 弹幕正文
     * </pre>
     *
     * <code>string content = 7;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 弹幕正文
     * </pre>
     *
     * <code>string content = 7;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      content_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 弹幕正文
     * </pre>
     *
     * <code>string content = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      content_ = getDefaultInstance().getContent();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 弹幕正文
     * </pre>
     *
     * <code>string content = 7;</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      content_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private long ctime_ ;
    /**
     * <pre>
     * 发送时间
     * </pre>
     *
     * <code>int64 ctime = 8;</code>
     * @return The ctime.
     */
    @Override
    public long getCtime() {
      return ctime_;
    }
    /**
     * <pre>
     * 发送时间
     * </pre>
     *
     * <code>int64 ctime = 8;</code>
     * @param value The ctime to set.
     * @return This builder for chaining.
     */
    public Builder setCtime(long value) {

      ctime_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送时间
     * </pre>
     *
     * <code>int64 ctime = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearCtime() {
      bitField0_ = (bitField0_ & ~0x00000080);
      ctime_ = 0L;
      onChanged();
      return this;
    }

    private int weight_ ;
    /**
     * <pre>
     * 权重 用于屏蔽等级 区间:[1,10]
     * </pre>
     *
     * <code>int32 weight = 9;</code>
     * @return The weight.
     */
    @Override
    public int getWeight() {
      return weight_;
    }
    /**
     * <pre>
     * 权重 用于屏蔽等级 区间:[1,10]
     * </pre>
     *
     * <code>int32 weight = 9;</code>
     * @param value The weight to set.
     * @return This builder for chaining.
     */
    public Builder setWeight(int value) {

      weight_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 权重 用于屏蔽等级 区间:[1,10]
     * </pre>
     *
     * <code>int32 weight = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeight() {
      bitField0_ = (bitField0_ & ~0x00000100);
      weight_ = 0;
      onChanged();
      return this;
    }

    private Object action_ = "";
    /**
     * <pre>
     * 动作
     * </pre>
     *
     * <code>string action = 10;</code>
     * @return The action.
     */
    public String getAction() {
      Object ref = action_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        action_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 动作
     * </pre>
     *
     * <code>string action = 10;</code>
     * @return The bytes for action.
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      Object ref = action_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 动作
     * </pre>
     *
     * <code>string action = 10;</code>
     * @param value The action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      action_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 动作
     * </pre>
     *
     * <code>string action = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      action_ = getDefaultInstance().getAction();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 动作
     * </pre>
     *
     * <code>string action = 10;</code>
     * @param value The bytes for action to set.
     * @return This builder for chaining.
     */
    public Builder setActionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      action_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private int pool_ ;
    /**
     * <pre>
     * 弹幕池 0:普通池 1:字幕池 2:特殊池(代码/BAS弹幕)
     * </pre>
     *
     * <code>int32 pool = 11;</code>
     * @return The pool.
     */
    @Override
    public int getPool() {
      return pool_;
    }
    /**
     * <pre>
     * 弹幕池 0:普通池 1:字幕池 2:特殊池(代码/BAS弹幕)
     * </pre>
     *
     * <code>int32 pool = 11;</code>
     * @param value The pool to set.
     * @return This builder for chaining.
     */
    public Builder setPool(int value) {

      pool_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 弹幕池 0:普通池 1:字幕池 2:特殊池(代码/BAS弹幕)
     * </pre>
     *
     * <code>int32 pool = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearPool() {
      bitField0_ = (bitField0_ & ~0x00000400);
      pool_ = 0;
      onChanged();
      return this;
    }

    private Object idStr_ = "";
    /**
     * <pre>
     * 弹幕dmid str
     * </pre>
     *
     * <code>string idStr = 12;</code>
     * @return The idStr.
     */
    public String getIdStr() {
      Object ref = idStr_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        idStr_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 弹幕dmid str
     * </pre>
     *
     * <code>string idStr = 12;</code>
     * @return The bytes for idStr.
     */
    public com.google.protobuf.ByteString
        getIdStrBytes() {
      Object ref = idStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        idStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 弹幕dmid str
     * </pre>
     *
     * <code>string idStr = 12;</code>
     * @param value The idStr to set.
     * @return This builder for chaining.
     */
    public Builder setIdStr(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      idStr_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 弹幕dmid str
     * </pre>
     *
     * <code>string idStr = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdStr() {
      idStr_ = getDefaultInstance().getIdStr();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 弹幕dmid str
     * </pre>
     *
     * <code>string idStr = 12;</code>
     * @param value The bytes for idStr to set.
     * @return This builder for chaining.
     */
    public Builder setIdStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      idStr_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    private int attr_ ;
    /**
     * <pre>
     * 弹幕属性位(bin求AND)
     * bit0:保护 bit1:直播 bit2:高赞
     * </pre>
     *
     * <code>int32 attr = 13;</code>
     * @return The attr.
     */
    @Override
    public int getAttr() {
      return attr_;
    }
    /**
     * <pre>
     * 弹幕属性位(bin求AND)
     * bit0:保护 bit1:直播 bit2:高赞
     * </pre>
     *
     * <code>int32 attr = 13;</code>
     * @param value The attr to set.
     * @return This builder for chaining.
     */
    public Builder setAttr(int value) {

      attr_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 弹幕属性位(bin求AND)
     * bit0:保护 bit1:直播 bit2:高赞
     * </pre>
     *
     * <code>int32 attr = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearAttr() {
      bitField0_ = (bitField0_ & ~0x00001000);
      attr_ = 0;
      onChanged();
      return this;
    }

    private Object animation_ = "";
    /**
     * <pre>
     * </pre>
     *
     * <code>string animation = 22;</code>
     * @return The animation.
     */
    public String getAnimation() {
      Object ref = animation_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        animation_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string animation = 22;</code>
     * @return The bytes for animation.
     */
    public com.google.protobuf.ByteString
        getAnimationBytes() {
      Object ref = animation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        animation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string animation = 22;</code>
     * @param value The animation to set.
     * @return This builder for chaining.
     */
    public Builder setAnimation(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      animation_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string animation = 22;</code>
     * @return This builder for chaining.
     */
    public Builder clearAnimation() {
      animation_ = getDefaultInstance().getAnimation();
      bitField0_ = (bitField0_ & ~0x00002000);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string animation = 22;</code>
     * @param value The bytes for animation to set.
     * @return This builder for chaining.
     */
    public Builder setAnimationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      animation_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bilibili.community.service.dm.v1.DanmakuElem)
  }

  // @@protoc_insertion_point(class_scope:bilibili.community.service.dm.v1.DanmakuElem)
  private static final DanmakuElem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DanmakuElem();
  }

  public static DanmakuElem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DanmakuElem>
      PARSER = new com.google.protobuf.AbstractParser<DanmakuElem>() {
    @Override
    public DanmakuElem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DanmakuElem> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<DanmakuElem> getParserForType() {
    return PARSER;
  }

  @Override
  public DanmakuElem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

